name: 'CI: parliament question'
on: [push]
jobs:
  ci:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - uses: guardian/actions-read-private-repos@v0.1.1
        with:
          private-ssh-keys: ${{ secrets.PRIVATE_INFRASTRUCTURE_CONFIG_DEPLOY_KEY }}
      - run: |
          npm install
          npm run build
          npm run package
      - name: CDK synth
        run: |
          npm install
          npm run build
          npm run lint
          npm run test
          npm run synth
        working-directory: cdk
      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v4
        with:
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          configPath: cdk/cdk.out/riff-raff.yaml
          projectName: investigations::parliament-questions
          # buildNumberOffset: 60
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out/parliament-questions-CODE.template.json
              - cdk/cdk.out/parliament-questions-PROD.template.json
            parliament-questions:
              - cdk/parliament-questions.zip
